theme: jekyll-theme-slate
title: Peter Lubulwa
author: GitHub User PLUBULWA
email: your-email@domain.com - CHECK IT OUT THEN KEEP GOING
description: > # this means to ignore newlines until "baseurl:"
  Personal profile
  Google search results) and in your feed.xml site description.
# social links
twitter_username: peterlubulwa # DO NOT include the @ character, or else the build will fail!
github_username:  plubulwa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
